// Verifies a Sign in with Apple `identityToken` (JWT) using Apple's public
// JWKS. Designed to run in Cloudflare Workers — uses Web Crypto, not Node's
// `crypto` module.
//
// The flow:
//   1. Split the JWT into header.payload.signature.
//   2. Decode the header to find the `kid` (key ID).
//   3. Fetch https://appleid.apple.com/auth/keys (cached for 1h via cf-cache)
//      and look up the matching JWK.
//   4. Import the JWK as an RSASSA-PKCS1-v1_5 / SHA-256 verification key.
//   5. Verify the signature over `header.payload`.
//   6. Parse the payload and assert `iss`, `aud`, `exp`.
//
// We do NOT validate `nonce` here — the caller passes the expected nonce
// (generated by the client and round-tripped through Apple) for an extra
// replay defense. Keeping it as an opt-in keeps the helper reusable for
// server-only flows that don't have a nonce.

const APPLE_ISSUER = 'https://appleid.apple.com'
const APPLE_JWKS_URL = 'https://appleid.apple.com/auth/keys'

export interface ApplePayload {
  iss: string
  aud: string | string[]
  exp: number
  iat: number
  sub: string
  email?: string
  email_verified?: boolean | 'true' | 'false'
  is_private_email?: boolean | 'true' | 'false'
  auth_time?: number
  nonce?: string
  nonce_supported?: boolean
}

interface JWK { kty: string; kid: string; use: string; alg: string; n: string; e: string }
let _keysCache: { keys: JWK[]; expires: number } | null = null

async function getAppleKeys(): Promise<JWK[]> {
  const now = Date.now()
  if (_keysCache && _keysCache.expires > now) return _keysCache.keys
  const res = await fetch(APPLE_JWKS_URL, { cf: { cacheTtl: 3600, cacheEverything: true } } as any)
  if (!res.ok) throw new Error('apple-jwks: fetch failed ' + res.status)
  const data: any = await res.json()
  if (!data || !Array.isArray(data.keys)) throw new Error('apple-jwks: malformed response')
  _keysCache = { keys: data.keys, expires: now + 60 * 60 * 1000 }
  return data.keys
}

function b64urlToBytes(s: string): Uint8Array {
  let t = s.replace(/-/g, '+').replace(/_/g, '/')
  while (t.length % 4) t += '='
  const bin = atob(t)
  const out = new Uint8Array(bin.length)
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i)
  return out
}

function b64urlToJson<T = any>(s: string): T {
  return JSON.parse(new TextDecoder().decode(b64urlToBytes(s)))
}

export async function verifyAppleIdentityToken(
  token: string,
  expectedAudiences: string[],
  expectedNonce?: string,
): Promise<ApplePayload> {
  if (!token || typeof token !== 'string') throw new Error('apple-jwt: missing token')
  const parts = token.split('.')
  if (parts.length !== 3) throw new Error('apple-jwt: malformed token')
  const header = b64urlToJson<{ alg: string; kid: string; typ?: string }>(parts[0])
  if (header.alg !== 'RS256') throw new Error('apple-jwt: unsupported alg ' + header.alg)
  if (!header.kid) throw new Error('apple-jwt: missing kid')

  const keys = await getAppleKeys()
  const jwk = keys.find((k) => k.kid === header.kid)
  if (!jwk) throw new Error('apple-jwt: unknown kid ' + header.kid)

  const cryptoKey = await crypto.subtle.importKey(
    'jwk',
    { kty: jwk.kty, n: jwk.n, e: jwk.e, alg: 'RS256', ext: true } as JsonWebKey,
    { name: 'RSASSA-PKCS1-v1_5', hash: { name: 'SHA-256' } },
    false,
    ['verify'],
  )

  const signedData = new TextEncoder().encode(parts[0] + '.' + parts[1])
  const signature = b64urlToBytes(parts[2])
  const valid = await crypto.subtle.verify({ name: 'RSASSA-PKCS1-v1_5' }, cryptoKey, signature, signedData)
  if (!valid) throw new Error('apple-jwt: bad signature')

  const payload = b64urlToJson<ApplePayload>(parts[1])
  if (payload.iss !== APPLE_ISSUER) throw new Error('apple-jwt: bad issuer ' + payload.iss)
  const auds = Array.isArray(payload.aud) ? payload.aud : [payload.aud]
  const okAud = auds.some((a) => expectedAudiences.includes(a))
  if (!okAud) throw new Error('apple-jwt: aud mismatch ' + auds.join(','))
  if (typeof payload.exp !== 'number' || payload.exp * 1000 < Date.now()) throw new Error('apple-jwt: expired')
  if (expectedNonce && payload.nonce && payload.nonce !== expectedNonce) throw new Error('apple-jwt: nonce mismatch')
  return payload
}
