// ============================================================
// Trace Training Data — few-shot retrieval for the auto-trace agent
// ============================================================
// Returns the N most similar past human-traced reports for a given
// property's footprint size + roof complexity. Used by
// services/auto-trace-agent.ts as Claude few-shot examples.
//
// Hybrid retrieval (per the design decision from 2026-05-10):
//   1. Static index — a curated JSON shipped with the worker bundle
//      (generated by scripts/build-traced-index.ts from the same SQL
//      as scripts/export-traced-reports.sql). Always present, fast,
//      survives D1 outages.
//   2. D1 live query — pulls the latest completed traces by
//      similarity. Source of truth as new reports complete.
//
// Both pools are merged, deduped by order_id, and ranked by a simple
// similarity score (sqft delta + segment-count delta + geographic
// proximity). D1 wins ties — fresher data takes priority.
// ============================================================

import type { Bindings } from '../types'
import { TRACED_INDEX, type TracedIndexEntry } from '../data/traced-index'
import type { AutoTraceEdge } from './auto-trace-agent'

export interface TrainingExample {
  order_id: number
  house_sqft: number | null
  roof_pitch_degrees: number | null
  complexity_class: string | null
  segments_count: number | null
  latitude: number | null
  longitude: number | null
  /** Raw stored trace — parsed at the call-site so we can pick the
   *  edge type the agent needs without re-shipping the entire payload. */
  roof_trace_json: string | object
}

export interface FetchTrainingArgs {
  edge: AutoTraceEdge
  centroidLat: number
  centroidLng: number
  targetSegments: number
  /** How many examples to return total. Defaults to 5 — past that the
   *  Claude prompt gets noisy and slower without measurable accuracy
   *  improvement on a one-off auto-trace pass. */
  limit?: number
  /** Optional sqft hint from the order. When unset we lean on
   *  geographic proximity + segment-count match. */
  targetSqft?: number
}

// ─────────────────────────────────────────────────────────────
// Public entry — merge static + D1 pools, score, return top-N
// ─────────────────────────────────────────────────────────────
export async function fetchTrainingExamples(env: Bindings, args: FetchTrainingArgs): Promise<TrainingExample[]> {
  const limit = args.limit ?? 5
  const live = await fetchLiveExamples(env, args)
  const merged = mergeUnique(live, TRACED_INDEX)

  // Filter: must have at least one segment of the requested edge type.
  // Otherwise the example is useless to the agent — eaves examples
  // give Claude no signal on how to draw hips.
  const usable = merged.filter(ex => exampleHasEdge(ex, args.edge))

  // Score: lower = better. Composed of normalized sqft delta, segment
  // delta, and geographic distance (km). Each component caps at 1.0 so
  // no single dimension dominates.
  const scored = usable.map(ex => ({
    ex,
    score: scoreExample(ex, args),
  })).sort((a, b) => a.score - b.score)

  return scored.slice(0, limit).map(s => s.ex)
}

// ─────────────────────────────────────────────────────────────
// D1 live query
// ─────────────────────────────────────────────────────────────
async function fetchLiveExamples(env: Bindings, args: FetchTrainingArgs): Promise<TrainingExample[]> {
  // Pull a candidate pool (top 30) ordered by recency. We re-rank in
  // memory because D1 doesn't support trig functions for great-circle
  // distance. 30 is plenty — the final filter shrinks this back to N.
  try {
    const rows = await env.DB.prepare(`
      SELECT o.id AS order_id, o.latitude, o.longitude, o.house_sqft,
             o.roof_trace_json,
             r.roof_pitch_degrees, r.complexity_class,
             r.roof_segments
      FROM orders o
      INNER JOIN reports r ON r.order_id = o.id
      WHERE o.roof_trace_json IS NOT NULL
        AND o.roof_trace_json != ''
        AND r.status = 'completed'
      ORDER BY o.id DESC
      LIMIT 30
    `).all<any>()
    return (rows.results || []).map(row => ({
      order_id: Number(row.order_id),
      house_sqft: row.house_sqft != null ? Number(row.house_sqft) : null,
      roof_pitch_degrees: row.roof_pitch_degrees != null ? Number(row.roof_pitch_degrees) : null,
      complexity_class: row.complexity_class || null,
      segments_count: countSegments(row.roof_segments),
      latitude: row.latitude != null ? Number(row.latitude) : null,
      longitude: row.longitude != null ? Number(row.longitude) : null,
      roof_trace_json: row.roof_trace_json,
    }))
  } catch (e: any) {
    console.warn('[trace-training] D1 query failed:', e?.message)
    return []
  }
}

// ─────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────
function countSegments(raw: any): number | null {
  if (raw == null) return null
  try {
    const parsed = typeof raw === 'string' ? JSON.parse(raw) : raw
    if (Array.isArray(parsed)) return parsed.length
    if (parsed && Array.isArray(parsed.segments)) return parsed.segments.length
  } catch { /* corrupt — fall through */ }
  return null
}

function mergeUnique(live: TrainingExample[], staticPool: TracedIndexEntry[]): TrainingExample[] {
  const byId = new Map<number, TrainingExample>()
  // D1 wins — insert it first so the static entries below skip dup ids.
  for (const ex of live) byId.set(ex.order_id, ex)
  for (const entry of staticPool) {
    if (byId.has(entry.order_id)) continue
    byId.set(entry.order_id, {
      order_id: entry.order_id,
      house_sqft: entry.house_sqft,
      roof_pitch_degrees: entry.roof_pitch_degrees,
      complexity_class: entry.complexity_class,
      segments_count: entry.segments_count,
      latitude: entry.latitude,
      longitude: entry.longitude,
      roof_trace_json: entry.roof_trace_json,
    })
  }
  return Array.from(byId.values())
}

function exampleHasEdge(ex: TrainingExample, edge: AutoTraceEdge): boolean {
  try {
    const trace = typeof ex.roof_trace_json === 'string' ? JSON.parse(ex.roof_trace_json) : ex.roof_trace_json
    if (!trace) return false
    if (edge === 'eaves') {
      return (Array.isArray(trace.eaves_sections) && trace.eaves_sections.length > 0)
          || (Array.isArray(trace.eaves) && trace.eaves.length >= 3)
    }
    if (edge === 'ridges') return Array.isArray(trace.ridges) && trace.ridges.length > 0
    if (edge === 'hips')   return Array.isArray(trace.hips)   && trace.hips.length > 0
  } catch { /* corrupt — skip */ }
  return false
}

function scoreExample(ex: TrainingExample, args: FetchTrainingArgs): number {
  const sqftDelta = (args.targetSqft != null && ex.house_sqft != null)
    ? Math.min(1, Math.abs(args.targetSqft - ex.house_sqft) / Math.max(args.targetSqft, 1))
    : 0.5
  const segDelta = (ex.segments_count != null && args.targetSegments > 0)
    ? Math.min(1, Math.abs(ex.segments_count - args.targetSegments) / Math.max(args.targetSegments, 1))
    : 0.5
  const distKm = (ex.latitude != null && ex.longitude != null)
    ? haversineKm(args.centroidLat, args.centroidLng, ex.latitude, ex.longitude)
    : 9999
  // Geographic distance is least important — same builder style only
  // matters within ~50 km. Past that the architecture mix is too
  // different to be useful as a similarity hint.
  const geoNorm = Math.min(1, distKm / 50)
  return sqftDelta * 0.45 + segDelta * 0.40 + geoNorm * 0.15
}

function haversineKm(aLat: number, aLng: number, bLat: number, bLng: number): number {
  const R = 6371
  const dLat = (bLat - aLat) * Math.PI / 180
  const dLng = (bLng - aLng) * Math.PI / 180
  const x = Math.sin(dLat / 2) ** 2
    + Math.cos(aLat * Math.PI / 180) * Math.cos(bLat * Math.PI / 180) * Math.sin(dLng / 2) ** 2
  return 2 * R * Math.asin(Math.sqrt(x))
}
