-- ============================================================
-- 0030: Report Search Embeddings
-- Stores vector embeddings for semantic search across roof reports.
-- Embeddings generated by Gemini text-embedding-004 (768 dimensions).
-- Cosine similarity computed server-side for search ranking.
-- ============================================================

CREATE TABLE IF NOT EXISTS report_embeddings (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  order_id INTEGER NOT NULL UNIQUE,
  -- The text that was embedded (for debugging / re-embedding)
  embedded_text TEXT NOT NULL,
  -- 768-dimension embedding vector stored as JSON array of floats
  embedding TEXT NOT NULL,
  -- Metadata for search result display (denormalized for speed)
  property_address TEXT,
  homeowner_name TEXT,
  total_footprint_sqft REAL,
  total_true_area_sqft REAL,
  roof_pitch TEXT,
  num_segments INTEGER,
  report_status TEXT,
  -- Timestamps
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_report_embeddings_order_id ON report_embeddings(order_id);
CREATE INDEX IF NOT EXISTS idx_report_embeddings_status ON report_embeddings(report_status);
