-- Storm Scout — Phase 3: territories + match history
-- Per-customer drawn polygons with alert thresholds + a log of matches
-- generated by the nightly ingest matcher.

CREATE TABLE IF NOT EXISTS storm_service_areas (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  customer_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  polygon_geojson TEXT NOT NULL,         -- GeoJSON Polygon coordinates (outer ring), stringified
  min_hail_inches REAL NOT NULL DEFAULT 1.0,
  min_wind_kmh INTEGER NOT NULL DEFAULT 0,
  types_json TEXT NOT NULL DEFAULT '["hail","wind","tornado","thunderstorm"]',
  notify_email INTEGER NOT NULL DEFAULT 1,
  notify_push INTEGER NOT NULL DEFAULT 0,
  is_active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_ssa_customer ON storm_service_areas(customer_id);
CREATE INDEX IF NOT EXISTS idx_ssa_active ON storm_service_areas(is_active);

CREATE TABLE IF NOT EXISTS storm_notifications (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  customer_id INTEGER NOT NULL,
  area_id INTEGER NOT NULL,
  area_name TEXT,
  event_source TEXT,                     -- 'eccc' | 'nws' | 'iem'
  event_type TEXT,                       -- 'hail' | 'wind' | 'tornado' | 'thunderstorm'
  severity TEXT,                         -- 'advisory' | 'watch' | 'warning' | 'extreme' | 'lsr'
  event_timestamp TEXT,
  matched_at TEXT DEFAULT (datetime('now')),
  hail_inches REAL,
  wind_kmh INTEGER,
  lat REAL,
  lng REAL,
  description TEXT,
  email_sent INTEGER NOT NULL DEFAULT 0,
  email_error TEXT,
  push_sent INTEGER NOT NULL DEFAULT 0,
  dedupe_key TEXT UNIQUE                 -- prevents double-notifying on re-runs
);

CREATE INDEX IF NOT EXISTS idx_sn_customer ON storm_notifications(customer_id, matched_at DESC);
CREATE INDEX IF NOT EXISTS idx_sn_area ON storm_notifications(area_id);
