SELECT
  o.id AS order_id,
  o.order_number,
  o.property_address,
  o.property_city,
  o.property_province,
  o.property_postal_code,
  o.latitude,
  o.longitude,
  o.service_tier,
  o.status AS order_status,
  o.payment_status,
  o.created_at AS order_created_at,
  o.roof_trace_json,
  o.trace_measurement_json,
  o.trace_source,
  o.needs_admin_trace,
  o.house_sqft,
  o.price_per_bundle,
  o.customer_notes,
  o.is_first_order,
  o.source,
  r.id AS report_id,
  r.roof_area_sqft,
  r.roof_area_sqm,
  r.roof_footprint_sqft,
  r.roof_footprint_sqm,
  r.area_multiplier,
  r.roof_pitch_degrees,
  r.roof_pitch_ratio,
  r.roof_azimuth_degrees,
  r.roof_segments,
  r.edge_measurements,
  r.total_ridge_ft,
  r.total_hip_ft,
  r.total_valley_ft,
  r.total_eave_ft,
  r.total_rake_ft,
  r.material_estimate,
  r.gross_squares,
  r.bundle_count,
  r.total_material_cost_cad,
  r.complexity_class,
  r.imagery_quality,
  r.imagery_date,
  r.confidence_score,
  r.confidence_breakdown,
  r.field_verification_recommended,
  r.report_version,
  r.engine_version,
  r.current_version_num,
  r.ai_measurement_json,
  r.ai_report_json,
  r.ai_status,
  r.ai_error,
  r.ai_analyzed_at,
  r.vision_findings_json,
  r.ai_generated_imagery_json,
  r.ai_imagery_status,
  r.damage_analysis_json,
  r.solar_panel_layout,
  r.measurement_metadata,
  r.facet_polygons_geo,
  r.production_simulation_json,
  r.needs_review,
  r.review_status,
  r.review_reason,
  r.review_detail,
  r.eaves_tags,
  r.weather_risk,
  r.status AS report_status,
  r.error_message AS report_error_message,
  r.created_at AS report_created_at,
  r.updated_at AS report_updated_at,
  r.generation_started_at,
  r.generation_completed_at,
  r.generation_attempts,
  r.share_view_count
FROM orders o
INNER JOIN reports r ON r.order_id = o.id
WHERE o.roof_trace_json IS NOT NULL AND o.roof_trace_json != ''
ORDER BY o.id ASC;
